Updated miniconda version in travis test
Necessary because downloading R and ape with miniconda3 3.7.3 was resulting in this error:
 
```
conda install --yes -n env_name -c r r-base r-ape
Fetching package metadata: ...
Solving package specifications: 
Error: Could not find some dependencies for r-base: _r-mutex 1.* anacondar_1
You can search for this package on Binstar with
    binstar search -t conda _r-mutex 1.* anacondar_1
You may need to install the Binstar command line client with
    conda install binstar
```